FROM mcr.microsoft.com/playwright:v1.18.1

RUN apt-get update &&\
  apt-get install software-properties-common -y &&\
  apt-add-repository universe -y &&\
  apt-get update &&\
  apt-get install maven -y
